[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
via_ir = false

[rpc_endpoints]
base = "https://mainnet.base.org"
base_sepolia = "https://sepolia.base.org"

[etherscan]
base = { key = "${BASE_SCAN_API_KEY}" }
base_sepolia = { key = "${BASE_SCAN_API_KEY}" }

